### ISSUE TITLE
Test failing on "Feature/add basic pages support" PR

### ISSUE THREAD

**Issue by bryanhuntesl** [edgurgel/tentacat#180]
Test failing - it's all copied and pasted but I'm not sure how to interpret the error on https://github.com/edgurgel/tentacat/pull/179/files 

<strike>

/code/bryanhuntesl/tentacat/ mix test test/pages_test.exs
Excluding tags: [skip: true]

  1) test get_info/3 (Tentacat.PagesTest)
     test/pages_test.exs:19
     ** (FunctionClauseError) no function clause matching in Tentacat.url/2

     The following arguments were given to Tentacat.url/2:
     
         # 1
         []
     
         # 2
         "/repos/edgurgel/ed-pages-site/pages"
     
     Attempted function clauses (showing 1 out of 1):
     
         defp url(_client = %Tentacat.Client{endpoint: endpoint}, path)
     
     code: get_info("edgurgel", "ed-pages-site", @client)
     stacktrace:
       (tentacat) lib/tentacat.ex:192: Tentacat.url/2
       (tentacat) lib/tentacat.ex:65: Tentacat.get/4
       test/pages_test.exs:21: (test)

Finished in 0.6 seconds
1 test, 1 failure

Randomized with seed 628845
</strike>

@edgurgel Any pointers on how to move past this ? 

Fixed it - now onto a second error - 
```
/code/bryanhuntesl/tentacat/ mix test test/pages_test.exs
Excluding tags: [skip: true]



  1) test get_info/3 (Tentacat.PagesTest)
     test/pages_test.exs:14
     ** (ExVCR.RequestNotMatchError) Request did not match with any one in the current cassette: test/fixture/vcr_cassettes/pages#get_info.json.
     Delete the current cassette with [mix vcr.delete] and re-record.
     
     Request: [:get, "https://api.github.com//repos/edgurgel/ed-pages-site/pages", [{"User-agent", "tentacat"}, {"Authorization", "token 8e663c8614ced27c09b963f806ac46776a29db50"}], "\"\\\"\\\"\"", []]
     
     code: assert get_info("edgurgel", "ed-pages-site", @client) != nil
     stacktrace:
       lib/exvcr/handler.ex:174: ExVCR.Handler.raise_error_if_cassette_already_exists/2
       lib/exvcr/handler.ex:145: ExVCR.Handler.get_response_from_server/3
       (httpoison) lib/httpoison/base.ex:633: HTTPoison.Base.request/9
       (tentacat) lib/tentacat.ex:2: Tentacat.request!/5
       (tentacat) lib/tentacat.ex:150: Tentacat.request_with_pagination/4
       (tentacat) lib/tentacat.ex:113: Tentacat.request_stream/5
       test/pages_test.exs:16: (test)



Finished in 0.9 seconds
1 test, 1 failure

Randomized with seed 63039
```

**Comment by bryanhuntesl** [comment]
Fixed by : https://github.com/edgurgel/tentacat/pull/179/commits/798fe5593ed55d44868f19f5659a13757a0f6c13
