### ISSUE TITLE
Unexpected failures running mix test

### ISSUE THREAD

**Issue by juddey** [edgurgel/tentacat#57]
Hi!

Just wanting to start creating a PR to support searching for users (its something I am working on atm).

Have cloned repo locally, but when I run 
```
MIX_ENV=test mix do deps.get, test
```
I get the following errors :disappointed:  

```
1) test followers/2 (Tentacat.FollowersTest)
     test/followers_test.exs:33
     ** (CaseClauseError) no case clause matching: {:error, {:undef, [{:cover, :is_compiled, [:hackney], []}, {:meck_proc, :get_cover_state, 1, [file: 'src/meck_proc.erl', line: 395]}, {:meck_proc, :backup_original, 3, [file: 'src/meck_proc.erl', line: 350]}, {:meck_proc, :init, 1, [file: 'src/meck_proc.erl', line: 204]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
     stacktrace:
       src/meck_proc.erl:112: :meck_proc.set_expect/2
       src/meck.erl:234: :meck.expect/3
       (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:604: Enum.each/2
       test/followers_test.exs:34

  2) test following?/3 (Tentacat.FollowersTest)
     test/followers_test.exs:45
     ** (CaseClauseError) no case clause matching: {:error, {:undef, [{:cover, :is_compiled, [:hackney], []}, {:meck_proc, :get_cover_state, 1, [file: 'src/meck_proc.erl', line: 395]}, {:meck_proc, :backup_original, 3, [file: 'src/meck_proc.erl', line: 350]}, {:meck_proc, :init, 1, [file: 'src/meck_proc.erl', line: 204]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
     stacktrace:
       src/meck_proc.erl:112: :meck_proc.set_expect/2
       src/meck.erl:234: :meck.expect/3
       (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:604: Enum.each/2
       test/followers_test.exs:46

  3) test unfollow/2 (Tentacat.FollowersTest)
     test/followers_test.exs:57
     ** (CaseClauseError) no case clause matching: {:error, {:undef, [{:cover, :is_compiled, [:hackney], []}, {:meck_proc, :get_cover_state, 1, [file: 'src/meck_proc.erl', line: 395]}, {:meck_proc, :backup_original, 3, [file: 'src/meck_proc.erl', line: 350]}, {:meck_proc, :init, 1, [file: 'src/meck_proc.erl', line: 204]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
     stacktrace:
       src/meck_proc.erl:112: :meck_proc.set_expect/2
       src/meck.erl:234: :meck.expect/3
       (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:604: Enum.each/2
       test/followers_test.exs:58
```

...a bunch more of the same errors go here....

```
 97) test delete/4 (Tentacat.Commits.CommentsTest)
     test/commits/comments_test.exs:55
     ** (CaseClauseError) no case clause matching: {:error, {:undef, [{:cover, :is_compiled, [:hackney], []}, {:meck_proc, :get_cover_state, 1, [file: 'src/meck_proc.erl', line: 395]}, {:meck_proc, :backup_original, 3, [file: 'src/meck_proc.erl', line: 350]}, {:meck_proc, :init, 1, [file: 'src/meck_proc.erl', line: 204]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
     stacktrace:
       src/meck_proc.erl:112: :meck_proc.set_expect/2
       src/meck.erl:234: :meck.expect/3
       (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
       (elixir) lib/enum.ex:604: Enum.each/2
       test/commits/comments_test.exs:56

..

Finished in 0.7 seconds (0.4s on load, 0.2s on tests)
105 tests, 97 failures, 7 invalid
```

This is my output from deps.get:

```
 MIX_ENV=test mix do deps.get, test
inch_ex is missing its version requirement, use ">= 0.0.0" if it should match any version
Running dependency resolution
Dependency resolution completed
  certifi: 0.3.0
  earmark: 0.1.19
  ex_doc: 0.8.4
  exactor: 2.2.0
  excoveralls: 0.4.5
  exjsx: 3.2.0
  exvcr: 0.7.1
  hackney: 1.4.8
  httpoison: 0.8.1
  idna: 1.0.3
  inch_ex: 0.4.0
  jsx: 2.6.2
  meck: 0.8.4
  mimerl: 1.0.2
  poison: 1.5.2
  ssl_verify_hostname: 1.0.5
```
New to elixir from ruby, so it might just be my setup, but not sure where to start looking. :smiley:

**Comment by edgurgel** [comment]
Can you share your erlang and elixir versions?

**Comment by juddey** [comment]
```
Erlang/OTP 18 [erts-7.2] [source] [64-bit] [smp:4:4] [async-threads:10] [kernel-poll:false]
Elixir 1.2.0
```

**Comment by edgurgel** [comment]
I think your system does not have the `cover` app that "comes" with erlang. More here: https://github.com/eproxus/meck/issues/148

**Comment by juddey** [comment]
Yep. that was it, thanks :dart:
